### ISSUE TITLE
New mundus fails to start.

### ISSUE THREAD

**Issue by krukhlis** [mbrlabs/Mundus#29]
After last tons of changes with assets there is an issue with mundus.
1) It can't start failing during startup with ArrayIndexOutOfBounds exception in the last project load code.
2) In order to cleanup any old artifacts of Mundus I have removed .mundus folder. After removal of the **.mundus** subfolder from the User's folder, Mundus fails to start with the following exception:

`
```
:editor:run[23:08][Fatal][Log] java.io.IOException: The system cannot find the path specified
	at java.io.WinNTFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1012)
	at com.mbrlabs.mundus.utils.Log.prepareLogFile(Log.java:92)
	at com.mbrlabs.mundus.utils.Log.init(Log.java:70)
	at com.mbrlabs.mundus.Main.main(Main.java:37)

[23:08][Fatal][Log] java.lang.NullPointerException
	at com.mbrlabs.mundus.utils.Log.prepareLogFile(Log.java:98)
	at com.mbrlabs.mundus.utils.Log.init(Log.java:70)
	at com.mbrlabs.mundus.Main.main(Main.java:37)

[23:08][Fatal][Log] Uncaught exception occurred, error report will be saved

Exception: java.lang.NullPointerException thrown from the UncaughtExceptionHandler in thread "main"
```
`
The problem is it doesn't create the .mundus subfolder under Windows user's folder. 
Also, just wondering -- is it typo or "as designed" -- the name of the log file is mundus**space**date.log?

**Comment by codenigma** [comment]
Had the same error.
I deleted the projects and the content of the folder .mundus, then it worked. I use ubuntu.
For the moment you can try create the .mundus folder in your home directory (i dont know the right location on windows) or remove the content of it, when its already present. This would reset mundus completely.

**Comment by mbrlabs** [comment]
Yes, i merged the assets branch into master. Lot's of suff regarding assets changed & the old files are not compatible any more. It's basically like Unity right now.

I can confirm the issue with the log file, same here. I never deleted the .mundus folder, just deleted it's content.
