### ISSUE TITLE
ERROR!

### ISSUE THREAD

**Issue by RMuskovets** [mbrlabs/Mundus#49]
I have an exception:
**java.io.FileNotFoundException:** C:\Users\LINKOR\.mundus\mundus.registry (Не удается найти указанный файл)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at com.mbrlabs.mundus.editor.core.kryo.KryoManager.loadRegistry(KryoManager.java:94)
	at com.mbrlabs.mundus.editor.Mundus.<init>(Mundus.kt:93)
	at com.mbrlabs.mundus.editor.Mundus.<clinit>(Mundus.kt:54)
	at com.mbrlabs.mundus.editor.Editor.create(Editor.kt:62)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.initializeListener(Lwjgl3Window.java:416)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:364)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:136)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:110)
	at com.mbrlabs.mundus.editor.Main.launchEditor(Main.kt:52)
	at com.mbrlabs.mundus.editor.Main.main(Main.kt:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
[09:08][Fatal][Log] **com.badlogic.gdx.utils.GdxRuntimeException:** java.lang.ExceptionInInitializerError
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:116)
	at com.mbrlabs.mundus.editor.Main.launchEditor(Main.kt:52)
	at com.mbrlabs.mundus.editor.Main.main(Main.kt:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: **java.lang.ExceptionInInitializerError**
	at com.mbrlabs.mundus.editor.Editor.setupInput(Editor.kt:96)
	at com.mbrlabs.mundus.editor.Editor.create(Editor.kt:70)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.initializeListener(Lwjgl3Window.java:416)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:364)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:136)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:110)
	... 7 more
Caused by: **com.badlogic.gdx.utils.GdxRuntimeException:** No com.badlogic.gdx.scenes.scene2d.ui.Window$WindowStyle registered with name: default
	at com.badlogic.gdx.scenes.scene2d.ui.Skin.get(Skin.java:154)
	at com.badlogic.gdx.scenes.scene2d.ui.Window.<init>(Window.java:61)
	at com.kotcrab.vis.ui.widget.VisWindow.<init>(VisWindow.java:52)
	at com.kotcrab.vis.ui.widget.VisWindow.<init>(VisWindow.java:47)
	at com.kotcrab.vis.ui.widget.file.FileChooser.<init>(FileChooser.java:170)
	at com.kotcrab.vis.ui.widget.file.FileChooser.<init>(FileChooser.java:162)
	at com.mbrlabs.mundus.editor.ui.UI.<init>(UI.kt:58)
	at com.mbrlabs.mundus.editor.ui.UI.<clinit>(UI.kt:47)
	... 13 more

[09:08][Fatal][Log] Uncaught exception occurred, error report will be saved
I ran Mundus in IntelliJ IDEA...

**Comment by mbrlabs** [comment]
mundus.registry is a file, which holds a list of all your projects. It's normally located in the user's home directory, but yours looks a bit weird. 
Can you check the value of HOME_DATA_FILE in editor/src/main/com/mbrlabs/mundus/editor/core/registry/Registry.java?
